### ISSUE TITLE
Suggestion: Use walls instead of journal notes

### ISSUE THREAD

**Issue by Nordiii** [knassher/FVTT-Teleport#13]
This would help with the setup for Stairs which are wider than one tile!
Maybe make it possible to connect a Journal note to a wall and make it a teleporter that way!

**Comment by knassher** [comment]
That would be hard to do but I Will take your suggestion and what can I do
with it.

Thanks

**Comment by ghero101** [comment]
> This would help with the setup for Stairs which are wider than one tile!
> Maybe make it possible to connect a Journal note to a wall and make it a teleporter that way!

Nordii,

What I have been doing for this is just changing the size of the icon, for example if you are playing with 70px squares, change the icon to be 240-250px it will now be 4 squares in size. If your stairs are 2 wide this works perfect with the collision he has added, since if an actor collide with either they are teleported, this way you can make virtually seemless transitions with multilevel maps.
